import type { INodeProperties } from 'n8n-workflow';

import {
	bodyCollectionField,
	bodyStringField,
	bodyOptionsField,
	byResource,
	queryNumberField,
	queryStringField,
	sortOrderField,
} from './helpers';

export const clientDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: byResource('client'),
		},
		default: 'getAll',
		options: [
			{ name: 'Get Many', value: 'getAll', action: 'Get many clients', routing: { request: { method: 'GET', url: '/clients' } } },
			{ name: 'Get', value: 'get', action: 'Get a client', routing: { request: { method: 'GET', url: '=/clients/{{$parameter.clientId}}' } } },
			{ name: 'Create', value: 'create', action: 'Create a client', routing: { request: { method: 'POST', url: '/clients' } } },
			{ name: 'Update', value: 'update', action: 'Update a client', routing: { request: { method: 'PUT', url: '=/clients/{{$parameter.clientId}}' } } },
		],
	},
	{
		displayName: 'Client ID',
		name: 'clientId',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: {
			show: {
				resource: ['client'],
				operation: ['get', 'update'],
			},
		},
	},
	bodyOptionsField(
		'Type',
		'clientCreateType',
		'client',
		['create'],
		'type',
		[
			{ name: 'Client', value: 'client' },
			{ name: 'Supplier', value: 'supplier' },
		],
		'client',
	),
	bodyStringField('Name', 'clientCreateName', 'client', ['create'], 'name', '', true),
	bodyStringField('Email', 'clientCreateEmail', 'client', ['create'], 'email'),
	bodyStringField('Phone', 'clientCreatePhone', 'client', ['create'], 'phone'),
	bodyStringField('Phone 2', 'clientCreatePhone2', 'client', ['create'], 'phone_2'),
	bodyStringField('Address Line 1', 'clientCreateAddressLine1', 'client', ['create'], 'address_line_1'),
	bodyStringField('Address Line 2', 'clientCreateAddressLine2', 'client', ['create'], 'address_line_2'),
	bodyStringField('Postal Code', 'clientCreatePostalCode', 'client', ['create'], 'postalcode'),
	bodyStringField('City', 'clientCreateCity', 'client', ['create'], 'city'),
	bodyStringField('Country', 'clientCreateCountry', 'client', ['create'], 'country'),
	bodyStringField('Country ID', 'clientCreateCountryId', 'client', ['create'], 'country_id'),
	bodyStringField('VAT Number', 'clientCreateVatNumber', 'client', ['create'], 'vat_number'),
	bodyStringField('CoC Number', 'clientCreateCocNumber', 'client', ['create'], 'coc_number'),
	bodyStringField('OIN', 'clientCreateOin', 'client', ['create'], 'oin'),
	bodyCollectionField('Update Fields', 'clientUpdateFields', 'client', ['update'], [
	bodyOptionsField(
		'Type',
		'type',
		'client',
		['update'],
		'type',
		[
			{ name: 'Client', value: 'client' },
			{ name: 'Supplier', value: 'supplier' },
		],
		'client',
	),
	bodyStringField('Name', 'name', 'client', ['update'], 'name'),
	bodyStringField('Email', 'email', 'client', ['update'], 'email'),
	bodyStringField('Phone', 'phone', 'client', ['update'], 'phone'),
	bodyStringField('Phone 2', 'phone2', 'client', ['update'], 'phone_2'),
	bodyStringField('Address Line 1', 'addressLine1', 'client', ['update'], 'address_line_1'),
	bodyStringField('Address Line 2', 'addressLine2', 'client', ['update'], 'address_line_2'),
	bodyStringField('Postal Code', 'postalCode', 'client', ['update'], 'postalcode'),
	bodyStringField('City', 'updateCity', 'client', ['update'], 'city'),
	bodyStringField('Country', 'updateCountry', 'client', ['update'], 'country'),
	bodyStringField('Country ID', 'updateCountryId', 'client', ['update'], 'country_id'),
	bodyStringField('VAT Number', 'updateVatNumber', 'client', ['update'], 'vat_number'),
	bodyStringField('CoC Number', 'updateCocNumber', 'client', ['update'], 'coc_number'),
	bodyStringField('OIN', 'updateOin', 'client', ['update'], 'oin'),
]),
	queryStringField('Search Query', 'clientQuery', 'client', ['getAll'], 'q'),
	queryStringField('Address Line 1', 'clientAddressLine1', 'client', ['getAll'], 'address_line_1'),
	queryStringField('City', 'clientCity', 'client', ['getAll'], 'city'),
	queryStringField('CoC Number', 'clientCocNumber', 'client', ['getAll'], 'coc_number'),
	queryNumberField('Contact ID', 'clientContactId', 'client', ['getAll'], 'contact_id', 0),
	queryStringField('Country', 'clientCountry', 'client', ['getAll'], 'country'),
	queryStringField('Email', 'clientEmail', 'client', ['getAll'], 'email'),
	queryStringField('Name', 'clientName', 'client', ['getAll'], 'name'),
	queryStringField('Phone', 'clientPhone', 'client', ['getAll'], 'phone'),
	queryStringField('Postal Code', 'clientPostalCode', 'client', ['getAll'], 'postalcode'),
	queryStringField('Reference', 'clientReference', 'client', ['getAll'], 'reference'),
	queryStringField('Sort By', 'clientSortBy', 'client', ['getAll'], 'sort_by', 'sort'),
	sortOrderField('clientSortOrder', 'client', ['getAll']),
	{
		displayName: 'Type',
		name: 'clientType',
		type: 'options',
		default: 'client',
		displayOptions: {
			show: {
				resource: ['client'],
				operation: ['getAll'],
			},
		},
		options: [
			{ name: 'Client', value: 'client' },
			{ name: 'Supplier', value: 'supplier' },
		],
		routing: {
			send: {
				type: 'query',
				property: 'type',
			},
		},
	},
	queryStringField('VAT Number', 'clientVatNumber', 'client', ['getAll'], 'vat_number'),
];
