import type { INodeProperties } from 'n8n-workflow';

import {
	bodyCollectionField,
	bodyJsonField,
	bodyNumberField,
	bodyOptionsField,
	bodyStringField,
	byResource,
	queryBooleanField,
	queryNumberField,
	queryStringField,
	sortOrderField,
} from './helpers';

export const eventDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: byResource('event'),
		},
		default: 'getAll',
		options: [
			{ name: 'Add Activities', value: 'addActivities', action: 'Add event activities', routing: { request: { method: 'POST', url: '=/events/{{$parameter.eventId}}/activities', body: '={{$parameter.eventActivitiesBody}}' } } },
			{ name: 'Add Products', value: 'addProducts', action: 'Add event products', routing: { request: { method: 'POST', url: '=/events/{{$parameter.eventId}}/products', body: '={{$parameter.eventProductsBody}}' } } },
			{ name: 'Create', value: 'create', action: 'Create an event', routing: { request: { method: 'POST', url: '/events' } } },
			{ name: 'Create Message', value: 'createMessage', action: 'Create event message', routing: { request: { method: 'POST', url: '=/events/{{$parameter.eventId}}/messages' } } },
			{ name: 'Delete', value: 'delete', action: 'Delete an event', routing: { request: { method: 'DELETE', url: '=/events/{{$parameter.eventId}}' } } },
			{ name: 'Delete Activity', value: 'deleteActivity', action: 'Delete event activity', routing: { request: { method: 'DELETE', url: '=/events/{{$parameter.eventId}}/activities/{{$parameter.activityId}}' } } },
			{ name: 'Get', value: 'get', action: 'Get an event', routing: { request: { method: 'GET', url: '=/events/{{$parameter.eventId}}' } } },
			{ name: 'Get Billed Amount', value: 'getBilledAmount', action: 'Get billed amount', routing: { request: { method: 'GET', url: '=/events/{{$parameter.eventId}}/billed_amount' } } },
			{ name: 'Get Many', value: 'getAll', action: 'Get many events', routing: { request: { method: 'GET', url: '/events' } } },
			{ name: 'Get Messages', value: 'getMessages', action: 'Get event messages', routing: { request: { method: 'GET', url: '=/events/{{$parameter.eventId}}/messages' } } },
			{ name: 'Update', value: 'update', action: 'Update an event', routing: { request: { method: 'PUT', url: '=/events/{{$parameter.eventId}}' } } },
			{ name: 'Update Activity', value: 'updateActivity', action: 'Update event activity', routing: { request: { method: 'PUT', url: '=/events/{{$parameter.eventId}}/activities/{{$parameter.activityId}}' } } },
			{ name: 'Update by Receipt', value: 'updateByReceipt', action: 'Update event from receipt', routing: { request: { method: 'POST', url: '=/events/{{$parameter.eventId}}/receipt', body: '={{$parameter.eventReceiptItemsBody}}' } } },
		],
	},
	{
		displayName: 'Event ID',
		name: 'eventId',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: {
			show: {
				resource: ['event'],
				operation: [
					'get',
					'update',
					'delete',
					'getMessages',
					'createMessage',
					'addActivities',
					'updateActivity',
					'deleteActivity',
					'addProducts',
					'updateByReceipt',
					'getBilledAmount',
				],
			},
		},
	},
	{
		displayName: 'Activity ID',
		name: 'activityId',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: {
			show: {
				resource: ['event'],
				operation: ['updateActivity', 'deleteActivity'],
			},
		},
	},
	queryStringField('Created After', 'eventCreatedAfter', 'event', ['getAll'], 'created_after'),
	queryStringField('Created Before', 'eventCreatedBefore', 'event', ['getAll'], 'created_before'),
	queryStringField('Date', 'eventDate', 'event', ['getAll'], 'date'),
	queryStringField('Event Date After', 'eventDateAfter', 'event', ['getAll'], 'event_date_after'),
	queryStringField('Event Date Before', 'eventDateBefore', 'event', ['getAll'], 'event_date_before'),
	queryStringField('Event IDs (Comma-Separated)', 'eventIds', 'event', ['getAll'], 'ids'),
	queryStringField('Exclude Event IDs (Comma-Separated)', 'eventNotIds', 'event', ['getAll'], 'not_ids'),
	queryStringField('Search Query', 'query', 'event', ['getAll'], 'q'),
	queryStringField('Sort By', 'eventSortBy', 'event', ['getAll'], 'sort_by', 'datetime_start'),
	queryStringField('Status (Comma-Separated)', 'eventStatus', 'event', ['getAll'], 'status'),
	queryStringField('Updated After', 'eventUpdatedAfter', 'event', ['getAll'], 'updated_after'),
	queryStringField('Updated Before', 'eventUpdatedBefore', 'event', ['getAll'], 'updated_before'),
	queryNumberField('Items Per Page', 'itemsPerPage', 'event', ['getAll'], 'items_per_page', 25, {
		minValue: 1,
		maxValue: 100,
	}),
	queryNumberField('Page', 'page', 'event', ['getAll'], 'page', 1, {
		minValue: 1,
	}),
	sortOrderField('eventSortOrder', 'event', ['getAll']),
	queryBooleanField('Include Activities', 'eventIncludeActivities', 'event', ['get', 'getAll'], 'include_activities'),
	queryBooleanField('Include Client', 'eventIncludeClient', 'event', ['get', 'getAll'], 'include_client'),
	queryBooleanField('Include Contacts', 'eventIncludeContacts', 'event', ['get', 'getAll'], 'include_contacts'),
	queryBooleanField('Include Deleted', 'eventIncludeDeleted', 'event', ['getAll'], 'include_deleted'),
	queryBooleanField('Include Location', 'eventIncludeLocation', 'event', ['get', 'getAll'], 'include_location'),
	queryBooleanField('Include Packages', 'eventIncludePackages', 'event', ['get', 'getAll'], 'include_packages'),
	queryBooleanField('Include Planner', 'eventIncludePlanner', 'event', ['get', 'getAll'], 'include_planner'),
	queryBooleanField('Include Products', 'eventIncludeProducts', 'event', ['get', 'getAll'], 'include_products'),
	queryBooleanField('Merge Products', 'eventMergeProducts', 'event', ['get', 'getAll'], 'merge_products'),
	queryStringField('Type', 'eventMessageType', 'event', ['getMessages'], 'type'),
	bodyStringField('Name', 'eventCreateName', 'event', ['create'], 'name', '', true),
	bodyNumberField('Location ID', 'eventCreateLocationId', 'event', ['create'], 'location_id', 0),
	bodyNumberField('Event Type ID', 'eventCreateEventTypeId', 'event', ['create'], 'event_type_id', 0),
	bodyNumberField('Client ID', 'eventCreateClientId', 'event', ['create'], 'client_id', 0),
	bodyNumberField('Planner ID', 'eventCreatePlannerId', 'event', ['create'], 'planner_id', 0),
	bodyStringField('Datetime Start', 'eventCreateDatetimeStart', 'event', ['create'], 'datetime_start'),
	bodyStringField('Datetime End', 'eventCreateDatetimeEnd', 'event', ['create'], 'datetime_end'),
	bodyStringField('Group Name', 'eventCreateGroupName', 'event', ['create'], 'group_name'),
	bodyStringField('Noticeboard Name', 'eventCreateNoticeboardName', 'event', ['create'], 'noticeboard_name'),
	bodyNumberField('Guests', 'eventCreateGuests', 'event', ['create'], 'guests', 0),
	bodyStringField('Locale', 'eventCreateLocale', 'event', ['create'], 'locale'),
	bodyStringField('Reference', 'eventCreateReference', 'event', ['create'], 'reference'),
	bodyStringField('Message', 'eventCreateMessageText', 'event', ['create'], 'message'),
	bodyJsonField('Extra Fields', 'eventCreateExtraFields', 'event', ['create'], 'extra_fields'),
	bodyStringField('Subject', 'eventMessageSubject', 'event', ['createMessage'], 'subject'),
	bodyStringField('Message', 'eventMessageBody', 'event', ['createMessage'], 'message', '', true),
	bodyOptionsField(
		'Type',
		'eventCreateMessageType',
		'event',
		['createMessage'],
		'type',
		[
			{ name: 'Message', value: 'message' },
			{ name: 'Note', value: 'note' },
		],
		'message',
	),
	bodyNumberField('Author ID', 'eventMessageAuthorId', 'event', ['createMessage'], 'author_id', 0),
	bodyStringField('Author First Name', 'eventMessageAuthorFirstName', 'event', ['createMessage'], 'author_first_name'),
	bodyStringField('Author Last Name', 'eventMessageAuthorLastName', 'event', ['createMessage'], 'author_last_name'),
	bodyStringField('Author Email', 'eventMessageAuthorEmail', 'event', ['createMessage'], 'author_email'),
	bodyCollectionField('Update Fields', 'eventUpdateFields', 'event', ['update'], [
	bodyStringField('Name', 'name', 'event', ['update'], 'name'),
	bodyNumberField('Location ID', 'locationId', 'event', ['update'], 'location_id', 0),
	bodyNumberField('Event Type ID', 'eventTypeId', 'event', ['update'], 'event_type_id', 0),
	bodyNumberField('Client ID', 'clientId', 'event', ['update'], 'client_id', 0),
	bodyNumberField('Planner ID', 'plannerId', 'event', ['update'], 'planner_id', 0),
	bodyStringField('Datetime Start', 'datetimeStart', 'event', ['update'], 'datetime_start'),
	bodyStringField('Datetime End', 'datetimeEnd', 'event', ['update'], 'datetime_end'),
	bodyStringField('Group Name', 'groupName', 'event', ['update'], 'group_name'),
	bodyStringField('Noticeboard Name', 'noticeboardName', 'event', ['update'], 'noticeboard_name'),
	bodyNumberField('Guests', 'guests', 'event', ['update'], 'guests', 0),
	bodyStringField('Locale', 'locale', 'event', ['update'], 'locale'),
	bodyStringField('Reference', 'reference', 'event', ['update'], 'reference'),
	bodyStringField('Message', 'message', 'event', ['update'], 'message'),
	bodyJsonField('Extra Fields', 'extraFields', 'event', ['update'], 'extra_fields'),
]),
	{
		displayName: 'Activities',
		name: 'eventActivitiesBody',
		type: 'json',
		default: '[]',
		required: true,
		displayOptions: {
			show: {
				resource: ['event'],
				operation: ['addActivities'],
			},
		},
		description: 'JSON array of activity objects to send as the request body',
	},
	bodyCollectionField('Activity Update Fields', 'eventUpdateActivityFields', 'event', ['updateActivity'], [
	bodyNumberField('Event Timeline ID', 'eventTimelineId', 'event', ['updateActivity'], 'event_timeline_id', 0),
	bodyNumberField('Location ID', 'locationId', 'event', ['updateActivity'], 'location_id', 0),
	bodyNumberField('Setup ID', 'setupId', 'event', ['updateActivity'], 'setup_id', 0),
	bodyStringField('Datetime Start', 'datetimeStart', 'event', ['updateActivity'], 'datetime_start'),
	bodyStringField('Datetime End', 'datetimeEnd', 'event', ['updateActivity'], 'datetime_end'),
	bodyStringField('Name', 'name', 'event', ['updateActivity'], 'name'),
	bodyStringField('Description', 'description', 'event', ['updateActivity'], 'description'),
	bodyNumberField('Guests', 'guests', 'event', ['updateActivity'], 'guests', 0),
	bodyStringField('Memo', 'memo', 'event', ['updateActivity'], 'memo'),
	bodyStringField('Internal Memo', 'internalMemo', 'event', ['updateActivity'], 'internal_memo'),
]),
	{
		displayName: 'Products',
		name: 'eventProductsBody',
		type: 'json',
		default: '[]',
		required: true,
		displayOptions: {
			show: {
				resource: ['event'],
				operation: ['addProducts'],
			},
		},
		description: 'JSON array of product objects to send as the request body',
	},
	{
		displayName: 'Receipt Items',
		name: 'eventReceiptItemsBody',
		type: 'json',
		default: '[]',
		required: true,
		displayOptions: {
			show: {
				resource: ['event'],
				operation: ['updateByReceipt'],
			},
		},
		description: 'JSON array of receipt item objects to send as the request body',
	},
];
