import type { INodeProperties } from 'n8n-workflow';

import {
	bodyNumberField,
	bodyOptionsField,
	bodyStringField,
	bodyBooleanField,
	byResource,
	queryBooleanField,
	queryNumberField,
	queryStringField,
	sortOrderField,
} from './helpers';

export const invoiceDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: byResource('invoice'),
		},
		default: 'getAll',
		options: [
			{ name: 'Add Payment', value: 'addPayment', action: 'Add invoice payment', routing: { request: { method: 'POST', url: '=/invoices/{{$parameter.invoiceId}}/payments' } } },
			{ name: 'Confirm Sync', value: 'confirmSync', action: 'Confirm invoice sync', routing: { request: { method: 'POST', url: '=/invoices/{{$parameter.invoiceId}}/sync/confirm' } } },
			{ name: 'Create', value: 'create', action: 'Create an invoice', routing: { request: { method: 'POST', url: '/invoices' } } },
			{ name: 'Get', value: 'get', action: 'Get an invoice', routing: { request: { method: 'GET', url: '=/invoices/{{$parameter.invoiceId}}' } } },
			{ name: 'Get File PDF', value: 'getFilePdf', action: 'Get an invoice PDF', routing: { request: { method: 'GET', url: '=/invoices/{{$parameter.invoiceId}}/file.pdf', json: false } } },
			{ name: 'Get Many', value: 'getAll', action: 'Get many invoices', routing: { request: { method: 'GET', url: '/invoices' } } },
		],
	},
	{
		displayName: 'Invoice ID',
		name: 'invoiceId',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: {
			show: {
				resource: ['invoice'],
				operation: ['addPayment', 'confirmSync', 'get', 'getFilePdf'],
			},
		},
	},
	queryStringField('Search Query', 'invoiceQuery', 'invoice', ['getAll'], 'q'),
	queryNumberField('Client ID', 'invoiceClientId', 'invoice', ['getAll'], 'client_id', 0),
	queryStringField('Created After', 'invoiceCreatedAfter', 'invoice', ['getAll'], 'created_after'),
	queryStringField('Created Before', 'invoiceCreatedBefore', 'invoice', ['getAll'], 'created_before'),
	queryStringField('Date', 'invoiceDate', 'invoice', ['getAll'], 'date'),
	queryBooleanField('Expired', 'invoiceExpired', 'invoice', ['getAll'], 'expired'),
	queryNumberField('Event ID', 'invoiceEventId', 'invoice', ['getAll'], 'event_id', 0),
	queryStringField('Sent After', 'invoiceSentAfter', 'invoice', ['getAll'], 'sent_after'),
	queryStringField('Sent Before', 'invoiceSentBefore', 'invoice', ['getAll'], 'sent_before'),
	queryStringField('Sort By', 'invoiceSortBy', 'invoice', ['getAll'], 'sort_by', 'sort'),
	queryStringField('Status (Comma-Separated)', 'invoiceStatus', 'invoice', ['getAll'], 'status'),
	sortOrderField('invoiceSortOrder', 'invoice', ['getAll']),
	queryNumberField('Page', 'invoicePage', 'invoice', ['getAll'], 'page', 1, {
		minValue: 1,
	}),
	queryNumberField('Items Per Page', 'invoiceItemsPerPage', 'invoice', ['getAll'], 'items_per_page', 25, {
		minValue: 1,
		maxValue: 100,
	}),
	bodyOptionsField(
		'Type',
		'invoiceCreateType',
		'invoice',
		['create'],
		'type',
		[
			{ name: 'Invoice', value: 'invoice' },
			{ name: 'External', value: 'external' },
		],
		'invoice',
	),
	bodyOptionsField(
		'Status',
		'invoiceCreateStatus',
		'invoice',
		['create'],
		'status',
		[
			{ name: 'Concept', value: 'concept' },
			{ name: 'Agreed', value: 'agreed' },
			{ name: 'Open', value: 'open' },
			{ name: 'Partially Paid', value: 'partiallypaid' },
			{ name: 'Paid', value: 'paid' },
			{ name: 'Credit', value: 'credit' },
			{ name: 'Cancelled', value: 'cancelled' },
		],
		'concept',
	),
	bodyStringField('Date Sent', 'invoiceCreateDateSent', 'invoice', ['create'], 'date_sent'),
	bodyNumberField('Event ID', 'invoiceCreateEventId', 'invoice', ['create'], 'event_id', 0),
	bodyStringField('Identifier', 'invoiceCreateIdentifier', 'invoice', ['create'], 'identifier'),
	bodyBooleanField('Include VAT', 'invoiceCreateInclVat', 'invoice', ['create'], 'incl_vat'),
	bodyStringField('Locale', 'invoiceCreateLocale', 'invoice', ['create'], 'locale'),
	bodyNumberField('Client ID', 'invoiceCreateClientId', 'invoice', ['create'], 'client_id', 0),
	bodyStringField('Client Name', 'invoiceCreateClientName', 'invoice', ['create'], 'client_name'),
	bodyStringField('Client Reference', 'invoiceCreateClientReference', 'invoice', ['create'], 'client_reference'),
	bodyStringField('Client First Name', 'invoiceCreateClientFirstName', 'invoice', ['create'], 'client_first_name'),
	bodyStringField('Client Last Name', 'invoiceCreateClientLastName', 'invoice', ['create'], 'client_last_name'),
	bodyStringField('Client Address Line 1', 'invoiceCreateClientAddressLine1', 'invoice', ['create'], 'client_address_line_1'),
	bodyStringField('Client Address Line 2', 'invoiceCreateClientAddressLine2', 'invoice', ['create'], 'client_address_line_2'),
	bodyStringField('Client Postal Code', 'invoiceCreateClientPostalCode', 'invoice', ['create'], 'client_postalcode'),
	bodyStringField('Client City', 'invoiceCreateClientCity', 'invoice', ['create'], 'client_city'),
	bodyStringField('Client Country', 'invoiceCreateClientCountry', 'invoice', ['create'], 'client_country'),
	bodyStringField('Client Country ID', 'invoiceCreateClientCountryId', 'invoice', ['create'], 'client_country_id'),
	bodyStringField('Client Email', 'invoiceCreateClientEmail', 'invoice', ['create'], 'client_email'),
	bodyStringField('Client VAT Number', 'invoiceCreateClientVatNumber', 'invoice', ['create'], 'client_vat_number'),
	bodyStringField('Client CoC Number', 'invoiceCreateClientCocNumber', 'invoice', ['create'], 'client_coc_number'),
	bodyStringField('Client OIN', 'invoiceCreateClientOin', 'invoice', ['create'], 'client_oin'),
	bodyNumberField('Payment Term', 'invoiceCreatePaymentTerm', 'invoice', ['create'], 'payment_term', 0),
	bodyNumberField('Amount', 'invoicePaymentAmount', 'invoice', ['addPayment'], 'amount', 0, true),
	bodyStringField('Date', 'invoicePaymentDate', 'invoice', ['addPayment'], 'date', '', true),
	bodyOptionsField(
		'Type',
		'invoicePaymentType',
		'invoice',
		['addPayment'],
		'type',
		[
			{ name: 'Bank Transfer', value: 'banktransfer' },
			{ name: 'Cash', value: 'cash' },
			{ name: 'Credit Card', value: 'creditcard' },
			{ name: 'Debit Card', value: 'debitcard' },
		],
		'cash',
		true,
	),
	bodyStringField('Provider', 'invoiceSyncProvider', 'invoice', ['confirmSync'], 'provider', '', true),
	bodyStringField('Datetime', 'invoiceSyncDatetime', 'invoice', ['confirmSync'], 'datetime', '', true),
	bodyStringField('External ID', 'invoiceSyncExternalId', 'invoice', ['confirmSync'], 'external_id'),
	bodyOptionsField(
		'Status',
		'invoiceSyncStatus',
		'invoice',
		['confirmSync'],
		'status',
		[
			{ name: 'Processed', value: 'processed' },
			{ name: 'Failed', value: 'failed' },
		],
		'processed',
		true,
	),
];
